/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinare;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openqa.selenium.By;
import org.openqa.selenium.Point;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 *
 * @author cobrel
 */
public class NewJFrame extends javax.swing.JFrame {

    FirefoxDriver driver;
    String url = "https://programare.vaccinare-covid.gov.ro/auth/login";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        start.setForeground(new java.awt.Color(0, 102, 102));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vaccinare");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 134, 111));

        usernameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usernameField.setToolTipText("");
        usernameField.setName(""); // NOI18N
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 30));

        passwordField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        try {

            System.setProperty("webdriver.gecko.driver", "C:\\Users\\crist\\Desktop\\vaccinare\\src\\resources\\geckodriver.exe");
            driver = new FirefoxDriver();
            driver.manage().window().setPosition(new Point(-2000, 0));
            driver.get(url);
            Robot robot = new Robot();
            for (int i = 0; i < 2; i++) {
                robot.keyPress(KeyEvent.VK_CONTROL);
                robot.keyPress(KeyEvent.VK_SUBTRACT);
                robot.keyPress(KeyEvent.VK_SUBTRACT);
                robot.keyRelease(KeyEvent.VK_SUBTRACT);
                robot.keyRelease(KeyEvent.VK_CONTROL);
            }
            String username = usernameField.getText();
            String parola = new String(passwordField.getPassword());
            WebDriverWait email = new WebDriverWait(driver, 20);
            email.until(ExpectedConditions.elementToBeClickable(By.id("mat-input-0"))).sendKeys(username);
            WebDriverWait password = new WebDriverWait(driver, 20);
            password.until(ExpectedConditions.elementToBeClickable(By.id("mat-input-1"))).sendKeys(parola);
            WebDriverWait autentifica = new WebDriverWait(driver, 20);
            autentifica.until(ExpectedConditions.elementToBeClickable(By.className("mat-button-wrapper"))).click();
            WebDriverWait beneficiari = new WebDriverWait(driver, 20);
            beneficiari.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Beneficiari')]"))).click();
            WebDriverWait programeaza = new WebDriverWait(driver, 20);
            programeaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'assignment_turned_in')]"))).click();

            while (true) {
                //Bucuresti
                WebDriverWait close = new WebDriverWait(driver, 20);
                close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                WebDriverWait filtru = new WebDriverWait(driver, 20);
                filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                WebDriverWait scrieBucuresti = new WebDriverWait(driver, 20);
                scrieBucuresti.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Bucuresti");
                WebDriverWait dropDownClick = new WebDriverWait(driver, 20);
                dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                WebDriverWait filtreaza = new WebDriverWait(driver, 20);
                filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();
                int Neghinita = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Eminescu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int policlinicaCotroceni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[4]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int fizioterapie = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[5]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int palatulCopiilorUnu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[8]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int RomexpoPatru = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[9]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int RomexpoCinci = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[10]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                if (Neghinita > 0 || Eminescu > 0 || policlinicaCotroceni > 0 || fizioterapie > 0 || palatulCopiilorUnu > 0 || RomexpoPatru > 0 || RomexpoCinci > 0) {
                    driver.manage().window().maximize();
                    break;
                }
                //da pagina
                WebDriverWait pagUrmatoare = new WebDriverWait(driver, 20);
                pagUrmatoare.until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/mat-paginator[1]/div[1]/div[1]/div[2]/button[2]/span[1]/*"))).click();
                int palatulCopiilorDoi = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                if (palatulCopiilorDoi > 0) {
                    driver.manage().window().maximize();
                    break;
                }
                //Ilfov 
                close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                WebDriverWait scrieIlfov = new WebDriverWait(driver, 20);
                scrieIlfov.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Ilfov");
                dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();

                int Jilava = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Clinceni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Glina = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int VoluntariUnu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[4]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Snagov = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[6]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Pantelimon = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[7]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int VoluntariDoi = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[8]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int spitalulPantelimon = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[9]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Buftea = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[10]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                if (Jilava > 0 || Clinceni > 0 || Glina > 0 || VoluntariUnu > 0 || Snagov > 0 || Pantelimon > 0 || VoluntariDoi > 0 || spitalulPantelimon > 0 || Buftea > 0) {
                    driver.manage().window().maximize();

                    break;
                }
                //da pagina
                WebDriverWait pagUrm = new WebDriverWait(driver, 20);
                pagUrm.until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/mat-paginator[1]/div[1]/div[1]/div[2]/button[2]/span[1]/*"))).click();
                int Otopeni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                int Balotesti = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                if (Otopeni > 0 || Balotesti > 0) {
                    driver.manage().window().maximize();

                    break;
                }

                //Ialomita
                close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                WebDriverWait scrieIalomita = new WebDriverWait(driver, 20);
                scrieIlfov.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Ialomita");
                dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();

                int Fetesti = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                if (Fetesti > 0) {
                    driver.manage().window().maximize();

                    break;
                }

            }
        } catch (AWTException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_startActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {

                System.setProperty("webdriver.gecko.driver", "C:\\Users\\crist\\Desktop\\vaccinare\\src\\resources\\geckodriver.exe");
                driver = new FirefoxDriver();
                driver.manage().window().setPosition(new Point(-2000, 0));
                driver.get(url);
                Robot robot = new Robot();
                for (int i = 0; i < 2; i++) {
                    robot.keyPress(KeyEvent.VK_CONTROL);
                    robot.keyPress(KeyEvent.VK_SUBTRACT);
                    robot.keyPress(KeyEvent.VK_SUBTRACT);
                    robot.keyRelease(KeyEvent.VK_SUBTRACT);
                    robot.keyRelease(KeyEvent.VK_CONTROL);
                }
                String username = usernameField.getText();
                String parola = new String(passwordField.getPassword());
                WebDriverWait email = new WebDriverWait(driver, 20);
                email.until(ExpectedConditions.elementToBeClickable(By.id("mat-input-0"))).sendKeys(username);
                WebDriverWait password = new WebDriverWait(driver, 20);
                password.until(ExpectedConditions.elementToBeClickable(By.id("mat-input-1"))).sendKeys(parola);
                WebDriverWait autentifica = new WebDriverWait(driver, 20);
                autentifica.until(ExpectedConditions.elementToBeClickable(By.className("mat-button-wrapper"))).click();
                WebDriverWait beneficiari = new WebDriverWait(driver, 20);
                beneficiari.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Beneficiari')]"))).click();
                WebDriverWait programeaza = new WebDriverWait(driver, 20);
                programeaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'assignment_turned_in')]"))).click();

                while (true) {
                    //Bucuresti
                    WebDriverWait close = new WebDriverWait(driver, 20);
                    close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                    WebDriverWait filtru = new WebDriverWait(driver, 20);
                    filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                    WebDriverWait scrieBucuresti = new WebDriverWait(driver, 20);
                    scrieBucuresti.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Bucuresti");
                    WebDriverWait dropDownClick = new WebDriverWait(driver, 20);
                    dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                    WebDriverWait filtreaza = new WebDriverWait(driver, 20);
                    filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();
                    int Neghinita = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Eminescu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int policlinicaCotroceni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[4]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int fizioterapie = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[5]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int palatulCopiilorUnu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[8]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int RomexpoPatru = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[9]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int RomexpoCinci = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[10]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    if (Neghinita > 0 || Eminescu > 0 || policlinicaCotroceni > 0 || fizioterapie > 0 || palatulCopiilorUnu > 0 || RomexpoPatru > 0 || RomexpoCinci > 0) {
                        driver.manage().window().maximize();
                        break;
                    }
                    //da pagina
                    WebDriverWait pagUrmatoare = new WebDriverWait(driver, 20);
                    pagUrmatoare.until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/mat-paginator[1]/div[1]/div[1]/div[2]/button[2]/span[1]/*"))).click();
                    int palatulCopiilorDoi = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    if (palatulCopiilorDoi > 0) {
                        driver.manage().window().maximize();
                        break;
                    }
                    //Ilfov 
                    close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                    filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                    WebDriverWait scrieIlfov = new WebDriverWait(driver, 20);
                    scrieIlfov.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Ilfov");
                    dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                    filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();

                    int Jilava = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Clinceni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Glina = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int VoluntariUnu = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[4]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Snagov = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[6]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Pantelimon = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[7]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int VoluntariDoi = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[8]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int spitalulPantelimon = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[9]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Buftea = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[10]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    if (Jilava > 0 || Clinceni > 0 || Glina > 0 || VoluntariUnu > 0 || Snagov > 0 || Pantelimon > 0 || VoluntariDoi > 0 || spitalulPantelimon > 0 || Buftea > 0) {
                        driver.manage().window().maximize();

                        break;
                    }
                    //da pagina
                    WebDriverWait pagUrm = new WebDriverWait(driver, 20);
                    pagUrm.until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/mat-paginator[1]/div[1]/div[1]/div[2]/button[2]/span[1]/*"))).click();
                    int Otopeni = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[1]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    int Balotesti = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[3]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    if (Otopeni > 0 || Balotesti > 0) {
                        driver.manage().window().maximize();

                        break;
                    }

                    //Ialomita
                    close.until(ExpectedConditions.elementToBeClickable(By.xpath("//mat-icon[contains(text(),'close')]"))).click();
                    filtru.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).click();
                    WebDriverWait scrieIalomita = new WebDriverWait(driver, 20);
                    scrieIlfov.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='mat-input-6']"))).sendKeys("Ialomita");
                    dropDownClick.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[@class='mat-option-text']"))).click();
                    filtreaza.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(text(),'Filtreaza')]"))).click();

                    int Fetesti = Integer.parseInt(new WebDriverWait(driver, 20).until(ExpectedConditions.elementToBeClickable(By.xpath("/html[1]/body[1]/app[1]/vertical-layout-1[1]/div[1]/div[1]/div[1]/div[1]/content[1]/app-new-appointment[1]/div[1]/div[2]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/div[1]/list-centres[1]/fuse-widget[1]/div[1]/div[1]/mat-table[1]/mat-row[2]/mat-cell[5]/mat-chip-list[1]/div[1]/mat-chip[1]"))).getText());
                    if (Fetesti > 0) {
                        driver.manage().window().maximize();

                        break;
                    }

                }
            } catch (AWTException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton start;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
