/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intGrafica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class adaugare_contact extends javax.swing.JFrame {

    /**
     * Creates new form adaugare_contact
     */
    public adaugare_contact() {
        initComponents();
    }
    
    public String format_adaugare_data_nasterii() throws ParseException {
        String data = adaugare_data_nasterii.getText();
        Date completionDate = new SimpleDateFormat("yyyy-MM-dd").parse(data);
        String date = new SimpleDateFormat("MM-dd").format(completionDate);
        return date;
    }
    
    public String getBirthday() {
        LocalDate ld = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM-dd");
        String date1 = ld.format(dtf);
        return date1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adaugare_nume = new javax.swing.JTextField();
        adaugare_data_nasterii = new javax.swing.JTextField();
        adaugare_numar_de_telefon = new javax.swing.JTextField();
        adaugare_prenume = new javax.swing.JTextField();
        tip_telefon_combo = new javax.swing.JComboBox<>();
        adauga_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nume : ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Prenume : ");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Data_nasterii : ");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Numar_de_telefon : ");

        adaugare_nume.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adaugare_nume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        adaugare_data_nasterii.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adaugare_data_nasterii.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        adaugare_numar_de_telefon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adaugare_numar_de_telefon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        adaugare_prenume.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adaugare_prenume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        adaugare_prenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugare_prenumeActionPerformed(evt);
            }
        });

        tip_telefon_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Fix" }));

        adauga_button.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adauga_button.setForeground(new java.awt.Color(0, 102, 102));
        adauga_button.setText("Adauga");
        adauga_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adauga_buttonActionPerformed(evt);
            }
        });

        cancel_button.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(0, 102, 102));
        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adaugare_nume, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(adaugare_prenume))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adauga_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adaugare_data_nasterii, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(adaugare_numar_de_telefon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(tip_telefon_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adaugare_nume, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adaugare_prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adaugare_data_nasterii, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(adaugare_numar_de_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tip_telefon_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(adauga_button))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adauga_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adauga_buttonActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app?user=test&password=test");
            String query = "INSERT INTO agendajava(Nume,Prenume,Data_nasterii,Numar_de_telefon,Tip_telefon)VALUES(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            String selectQuery = "SELECT * FROM agendajava";
            ResultSet rs = pst.executeQuery(selectQuery);
            
            if ((adaugare_nume.getText().length() >=2 && adaugare_prenume.getText().length() >= 2) && ((adaugare_numar_de_telefon.getText().startsWith("07") == true &&  adaugare_numar_de_telefon.getText().length() == 10 && tip_telefon_combo.getSelectedItem().toString().equals("Mobil")) || (adaugare_numar_de_telefon.getText().startsWith("02") == true &&  adaugare_numar_de_telefon.getText().length() == 10 && tip_telefon_combo.getSelectedItem().toString().equals("Fix")) || (adaugare_numar_de_telefon.getText().startsWith("03") == true &&  adaugare_numar_de_telefon.getText().length() == 10 && tip_telefon_combo.getSelectedItem().toString().equals("Fix")))) {
                pst.setString(1, adaugare_nume.getText());
                pst.setString(2, adaugare_prenume.getText());
                pst.setString(3, adaugare_data_nasterii.getText());
                pst.setString(4, adaugare_numar_de_telefon.getText());
                String tip_telefon;
                tip_telefon = tip_telefon_combo.getSelectedItem().toString();
                pst.setString(5, tip_telefon);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, " Succes! ", "Adaugare Contact", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid contact", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            if(format_adaugare_data_nasterii().equals(getBirthday())) {
               JOptionPane.showMessageDialog(this, " Aceasta persoana isi serbeaza ziua nasterii astazi ", "La multi ani!", JOptionPane.PLAIN_MESSAGE); 
            }

            dispose();
            Agenda a = new Agenda();
            a.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Contact duplicat", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_adauga_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        Agenda a = new Agenda();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void adaugare_prenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugare_prenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adaugare_prenumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adaugare_contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adaugare_contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adaugare_contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adaugare_contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adaugare_contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adauga_button;
    private javax.swing.JTextField adaugare_data_nasterii;
    private javax.swing.JTextField adaugare_numar_de_telefon;
    private javax.swing.JTextField adaugare_nume;
    private javax.swing.JTextField adaugare_prenume;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tip_telefon_combo;
    // End of variables declaration//GEN-END:variables
}
